# NUMPY 101

Numpy為一個Python的矩陣運算函式庫，包含了基本的矩陣運算、線性代數、隨機變數產生、以及一些相關的計算功能。令一個兄弟函式庫為scipy，為Scientific Python的縮寫。這兩個函式庫涵蓋了所有本課程會用到的功能，而其中又以numpy為大宗。因此我們將會以numpy為主角。

我們在這個單元將會介紹基本的矩陣運算。如果想要更深入的了解，網路上有豐富的資源，如：
Python Linear Algebra Cheat Sheet: https://s3.amazonaws.com/assets.datacamp.com/blog_assets/Python_SciPy_Cheat_Sheet_Linear_Algebra.pdf

或是參考numpy網站以及scipy網站上的文件：
* https://numpy.org/
* https://www.scipy.org/

以及這些網頁：
* http://rlhick.people.wm.edu/stories/linear-algebra-python-basics.html
* https://jakevdp.github.io/PythonDataScienceHandbook/02.02-the-basics-of-numpy-arrays.html


### 建構矩陣

首先由建構向量與矩陣開始。在使用之前必須先import numpy:

In [1]:
import numpy as np

接下來我們來建構第一個向量，一個Row Vector

In [2]:
r1 = np.array([1, 2, 3.3])
print(r1)

[1.  2.  3.3]


跟Column Vector比較一下：

In [3]:
c1 = np.array([[1], 
             [2], 
             [3]])
print(c1)

[[1]
 [2]
 [3]]


In [4]:
c1

array([[1],
       [2],
       [3]])

實際上，上面的Row Vector是一個 $1 \times 3$的陣列(Array)，而Column Vector則是一個$3 \times 1$的陣列。這個課程討論的矩陣是兩個維度，因此也只會用的二維的矩陣。

我們可以透過`.shape`得到一個array的大小，比如說：

In [4]:
print(c1.shape)

(3, 1)


不過`r1`就有點怪怪的：

In [5]:
print(r1.shape)

(3,)


回傳的`(3,)`代表r1是一個一維的陣列，而c1是一個二維的陣列。這件事在後續的計算會再遇到。目前先在這裡打住。

要特別說明的是，因為我們使用一維與二維陣列代表向量與矩陣，這些名詞會交替使用。

我們來建構一個$4\times 3$的矩陣。

In [5]:
m1 = np.array([[1, 2, 3], 
               [2, 3, 5], 
               [5.2, 9, 12],
               [-3, 22, 7]])
print(m1)

[[ 1.   2.   3. ]
 [ 2.   3.   5. ]
 [ 5.2  9.  12. ]
 [-3.  22.   7. ]]


In [6]:
m1.shape

(4, 3)

另外numpy有提供一些函數方便大家建構特殊的矩陣。比如說

In [7]:
#Create an array of all zeros
ex1 = np.zeros((3, 3))
print(ex1)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [8]:
#Create an array of all ones
ex2 = np.ones((2, 3))
print(ex2)

[[1. 1. 1.]
 [1. 1. 1.]]


In [9]:
#Create a constant array
ex3 = np.full((3, 2), 5.2)
print(ex3)

[[5.2 5.2]
 [5.2 5.2]
 [5.2 5.2]]


In [10]:
#Create an identity matrix
ex4 = np.eye(3)
print(ex4)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [12]:
#Random matrix (隨機矩陣), draw from Uniform(0, 1)
ex5 = np.random.random((4, 4))
print(ex5)

[[0.07948145 0.93524253 0.40547127 0.34074214]
 [0.84779042 0.25150756 0.54336106 0.83650513]
 [0.04462102 0.88618739 0.55128531 0.47274217]
 [0.30129341 0.52929371 0.32960264 0.55869939]]


## 基本運算

我們會使用numpy中定義的array運算來實現矩陣的計算。必須要記在心裡的是，矩陣跟陣列畢竟是不一樣的東西，要小心使用才能有正確（預期）的結果。

我們先看簡單的狀況：形狀一樣的陣列相加。

In [13]:
c3 = np.array([[1], 
             [2.5], 
             [3]])
print("c3 = \n", c3)

c4 = np.array([[-12], 
             [5], 
             [-1]])
print("c4 = \n", c4)

c3 = 
 [[1. ]
 [2.5]
 [3. ]]
c4 = 
 [[-12]
 [  5]
 [ -1]]


形狀一樣的陣列相加就是把對應的元素加起來。結果的形狀跟原來是一樣的。

In [14]:
print(c3+c4)

[[-11. ]
 [  7.5]
 [  2. ]]


那如果形狀不一樣的陣列可以相加嗎？
如果我們把陣列看成矩陣，應該要預期跳出錯誤訊息。不過實際上為了計算方便，應付實際上可能會遇到的狀況，numpy允許你把兩個形狀不一樣的矩陣相加。比如說：

In [15]:
#shape = (3,)
print(r1)

[1.  2.  3.3]


In [16]:
#shape(3, 1)
print(c1)

[[1]
 [2]
 [3]]


In [17]:
#add two array of different shapes
madd1 = r1+c1
print(madd1)

[[2.  3.  4.3]
 [3.  4.  5.3]
 [4.  5.  6.3]]


可以看到`r1+c1`產生了一個 $3 \times 3$的陣列。裡面的數值是把r1看成一個$1 \times 3$的陣列，然後在結果矩陣的每一個位置取相對的r1與c1的值相加。舉例而言，madd1中(1,2)位置的值為取c1的第一個位置的值(1)與r1第二個位置的值(2)相加的到的(=3)。

這個行為在numpy中稱為broadcasting。在遇到真的問題時很有用，不過也常會讓初學者混淆。

### 牛刀小試

建構一個叫r5的Row Vector，裡面的值為1, 2, 3, 4。將r5與c1相加。在還沒實際執行程式碼之前，想想
* 回傳的陣列形狀是什麼？
* 裡面的值會是什麼？

In [18]:
# 有空間才能思考
















In [18]:
# 參考解答

r5 = np.array([1, 2, 3, 4])
madd2 = r5 + c1
print("madd2 = \n", madd2)
print("the shape is: ", madd2.shape)

madd2 = 
 [[2 3 4 5]
 [3 4 5 6]
 [4 5 6 7]]
the shape is:  (3, 4)


以下我們的討論會以陣列的形狀相同為前提。

先定義`m2`與`m3`:

In [19]:
m2 = np.array([[1, 2, 3], 
               [2, 3, 5]])
print(m2)

[[1 2 3]
 [2 3 5]]


In [20]:
m3 = np.array([[2, 1], 
               [1, 1], 
               [-1, 1]])
print(m3)

[[ 2  1]
 [ 1  1]
 [-1  1]]


矩陣乘法為`np.dot()`，所以$m2 \cdot m3$是

In [21]:
mb1 = np.dot(m2, m3)
print(mb1)

[[ 1  6]
 [ 2 10]]


而$m3 \cdot m2$是：

In [23]:
mb2 = np.dot(m3, m2)
print(mb2)

[[ 4  7 11]
 [ 3  5  8]
 [ 1  1  2]]


轉置 (transpose)是

In [24]:
np.transpose(m2)

array([[1, 2],
       [2, 3],
       [3, 5]])

另一個作法是取用原陣列的屬性`.T`

In [25]:
m2.T

array([[1, 2],
       [2, 3],
       [3, 5]])

至於反矩陣則是`np.linalg.inv()`

In [22]:
m4 = np.array([[1, 2], 
              [3, 4]])
invm4 = np.linalg.inv(m4)
print(invm4)

[[-2.   1. ]
 [ 1.5 -0.5]]


In [24]:
#check the correctness
#如果乘起來不是Identity Matrix就去買樂透

print(np.dot(m4, invm4))

[[1.00000000e+00 1.11022302e-16]
 [0.00000000e+00 1.00000000e+00]]


In [25]:
print(np.dot(invm4, m4))

[[1.0000000e+00 4.4408921e-16]
 [0.0000000e+00 1.0000000e+00]]


現在大家的電腦都很快，何不算一個大一點的矩陣？

In [26]:
m5 = np.random.random((5, 5))
invm5 = np.linalg.inv(m5)
print(invm5)

[[ -1.31739656  -4.01398237   7.10114299  -1.73000682  -2.63971205]
 [  0.18616291  -4.42292252   7.15956637  -2.27196027  -3.78437177]
 [  0.20958999   3.46906413  -3.88203219   0.05078232   2.74259761]
 [  0.16567911  -6.14302343   5.89831225  -0.68391288  -2.87996607]
 [  1.37989539  16.4871088  -20.9273775    6.20439054   9.16117675]]


In [27]:
#檢查正確性

print(np.dot(m5, invm5))

[[ 1.00000000e+00 -2.42595305e-16  1.27124989e-15 -6.38567697e-17
  -2.37191126e-16]
 [ 1.00193723e-16  1.00000000e+00 -9.53463742e-17  2.11769991e-16
   6.21493015e-17]
 [ 1.62113091e-17  9.31033308e-17  1.00000000e+00  1.41203794e-16
   5.40991823e-16]
 [-1.15039088e-16  6.86527808e-16 -2.64311763e-15  1.00000000e+00
   8.28486452e-16]
 [ 7.44464847e-17  7.64741857e-16 -9.39604545e-16  7.55615873e-17
   1.00000000e+00]]


In [28]:
# 有時候Scientific Notation讓人看不清楚，何不關掉先？

np.set_printoptions(suppress=True)
print(np.dot(m5, invm5))

[[ 1. -0.  0. -0. -0.]
 [ 0.  1. -0.  0.  0.]
 [ 0.  0.  1.  0.  0.]
 [-0.  0. -0.  1.  0.]
 [ 0.  0. -0.  0.  1.]]


## 其他操作與子陣列

numpy有一個跟range很像的東西，叫np.arange()。

In [32]:
#create an array of 0 to 9
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
#create an array of 11 to 20
np.arange(11, 21)

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [34]:
#create an array of 12, 14, 16
np.arange(12, 17, 2)

array([12, 14, 16])

### 牛刀小試

利用np.arange()建立這個陣列： array([2, 4, 6, 8, 10])

In [35]:
# 有空間才能思考











In [30]:
# 參考解答

np.arange(2, 11, 2)

array([ 2,  4,  6,  8, 10])

***

操作numpy陣列一個很重要的技巧叫indexing，大致上的意思是由一個陣列中取出部份我們需要的元素。

這一系列的操作最完整的文件在這裡：
https://docs.scipy.org/doc/numpy/reference/arrays.indexing.html
    
我們將會針對一些比較常用的操作說明。你應該要找時間把上面的連結好好看一下。

第一件事要強調所有的Index都是由0開始。我們先由一維矩陣的切片(Slicing)開始說明。基本的語法是`i:j:k`，其中`i`是開始的index, `j`是結束的index, `k`是一次跳多少。這跟前面np.arange的三個參數是一樣的意思。

In [31]:
x = np.array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])
x[1:7:2]

array([11, 13, 15])

跟Python Indexing的語法一致，numpy也支援負數的Index，意思是由後面數過來。比如說倒數第一個元素是：

In [32]:
x[-1]

19

取最後五個：

In [33]:
x[-5:]

array([15, 16, 17, 18, 19])

取最後五個，但順序到過來：

In [34]:
x[-1:-6:-1]

array([19, 18, 17, 16, 15])

類似的語法也可以二維的陣列上。考慮下面的x2

In [35]:
x2 = np.array([[10, 11, 12, 13, 14, 15, 16],
               [50, 51, 52, 53, 54, 55, 56], 
               [70, 71, 72, 73, 74, 75, 76]])
x2

array([[10, 11, 12, 13, 14, 15, 16],
       [50, 51, 52, 53, 54, 55, 56],
       [70, 71, 72, 73, 74, 75, 76]])

我們可以取Row 1與Columns 2, 3:

In [36]:
x2[1, 2:4]

array([52, 53])

或是取取Row 1,2 與Columns 2, 3:

In [37]:
x2[1:3, 2:4]

array([[52, 53],
       [72, 73]])

以上所介紹的叫Basic Indexing。這種Indexing and Slicing的方式有一個很重要的特性，就是回傳的東西是原來陣列的一個View。也就是說，回傳的東西與原來的陣列是連動的。這個特性如果沒有弄清楚常會造成程式 **不可預期的錯誤** 。

要展示這個問題，我們考慮一個新的變數x5:

In [38]:
x5 = np.array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])
x5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [39]:
# 取位置3之後的元素

subx1 = x5[3:]
subx1

array([13, 14, 15, 16, 17, 18, 19])

In [40]:
# 將取出的子陣列中第三個位置的值改變

subx1[3] = 5
subx1

array([13, 14, 15,  5, 17, 18, 19])

In [41]:
# 這個操作也會影響到原來的變數

x5

array([10, 11, 12, 13, 14, 15,  5, 17, 18, 19])

Numpy還有另一種取子陣列的方式，叫Advanced Indexing。這種作法是利用一個list或tuple取出想要的元素。比如我們想要x中位置2, 3, 7的元素，可以這樣做：

In [42]:
subx2= x[[2, 3, 7]]
subx2

array([12, 13, 17])

這種作法比較有彈性，而且跟前面Basic Indexing最大的不同是，回傳的物件是原物件的一個copy，而不是view。也就是說，更動這個回傳的物件不會影響原來物件的數值。

請看下面的例子：

In [43]:
subx2[0] = -5
subx2

array([-5, 13, 17])

In [44]:
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [46]:
#copy a numpy variable
subx3 = subx1.copy()
subx3

array([13, 14, 15,  5, 17, 18, 19])

In [47]:
subx3[-1] = -9
subx3

array([13, 14, 15,  5, 17, 18, -9])

In [48]:
x5

array([10, 11, 12, 13, 14, 15,  5, 17, 18, 19])

# 牛刀小試

生成下面的矩陣：

```array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])```

In [ ]:
# 有空間才能思考









In [49]:
# 參考解答

z1 = np.zeros((4, 6))
z1

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

# 牛刀小試

生成下面的矩陣：

```array([[0., 1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6., 7.],
       [3., 4., 5., 6., 7., 8.]])```

In [59]:
# 有空間才能思考









In [50]:
# 參考解答
z2 = np.zeros((4, 6))
for i in range(4):
    z2[i,] = range(i, i+6)
    
z2

array([[0., 1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5., 6.],
       [2., 3., 4., 5., 6., 7.],
       [3., 4., 5., 6., 7., 8.]])

# 牛刀小試

生成下面的矩陣：

```array([[1. , 0.5, 0. , 0. , 0. ],
       [0.3, 1. , 0.5, 0. , 0. ],
       [0. , 0.3, 1. , 0.5, 0. ],
       [0. , 0. , 0.3, 1. , 0.5],
       [0. , 0. , 0. , 0.3, 1. ]])```

In [61]:
# 有空間才能思考









In [51]:
# 參考解答
z3 = np.eye(5)
for i in range(4):
    z3[i, i+1] = 0.5
    z3[i+1, i] = 0.3
    
z3

array([[1. , 0.5, 0. , 0. , 0. ],
       [0.3, 1. , 0.5, 0. , 0. ],
       [0. , 0.3, 1. , 0.5, 0. ],
       [0. , 0. , 0.3, 1. , 0.5],
       [0. , 0. , 0. , 0.3, 1. ]])